<link rel="stylesheet" href="{{ asset('assets/vendor/bootstrap/dist/css/bootstrap.min.css') }}">
<link rel="stylesheet" href="{{ asset('assets/vendor/ionicons/css/ionicons.min.css') }}">
<link rel="stylesheet" href="{{ asset('assets/vendor/flickity/dist/flickity.min.css') }}">
<link rel="stylesheet" href="{{ asset('assets/vendor/photoswipe/dist/photoswipe.css') }}">
<link rel="stylesheet" href="{{ asset('assets/vendor/photoswipe/dist/default-skin/default-skin.css') }}">
<link rel="stylesheet" href="{{ asset('assets/vendor/bootstrap-slider/dist/css/bootstrap-slider.min.css') }}">
<link rel="stylesheet" href="{{ asset('assets/vendor/summernote/dist/summernote-bs4.css') }}">
<link rel="stylesheet" href="{{ asset('assets/css/main.css') }}">
<link rel="stylesheet" href="{{ asset('assets/css/custom.css') }}">
