<script src="{{ asset('assets/vendor/jquery/3.7.1/jquery.min.js') }}"></script>
<script src="{{ asset('assets/vendor/rating-star-icons/rating.js') }}"></script>
<script src="{{ asset('assets/vendor/fontawesome/fontawesome.min.js') }}" crossorigin="anonymous"></script>
<script src="{{ asset('assets/vendor/object-fit-images/dist/ofi.min.js') }}"></script>
<script src="{{ asset('assets/vendor/gsap/src/minified/TweenMax.min.js') }}"></script>
<script src="{{ asset('assets/vendor/gsap/src/minified/plugins/ScrollToPlugin.min.js') }}"></script>
<script src="{{ asset('assets/vendor/bootstrap/dist/js/bootstrap.min.js') }}"></script>
<script src="{{ asset('assets/vendor/popper.js/dist/umd/popper.min.js') }}"></script>
<script src="{{ asset('assets/vendor/sticky-kit/dist/sticky-kit.min.js') }}"></script>
<script src="{{ asset('assets/vendor/jarallax/dist/jarallax.min.js') }}"></script>
<script src="{{ asset('assets/vendor/jarallax/dist/jarallax-video.min.js') }}"></script>
<script src="{{ asset('assets/vendor/imagesloaded/imagesloaded.pkgd.min.js') }}"></script>
<script src="{{ asset('assets/vendor/flickity/dist/flickity.pkgd.min.js') }}"></script>
<script src="{{ asset('assets/vendor/photoswipe/dist/photoswipe.min.js') }}"></script>
<script src="{{ asset('assets/vendor/photoswipe/dist/photoswipe-ui-default.min.js') }}"></script>
<script src="{{ asset('assets/vendor/jquery-validation/dist/jquery.validate.min.js') }}"></script>
<script src="{{ asset('assets/vendor/jquery-countdown/dist/jquery.countdown.min.js') }}"></script>
<script src="{{ asset('assets/vendor/moment/min/moment.min.js') }}"></script>
<script src="{{ asset('assets/vendor/moment-timezone/builds/moment-timezone-with-data.min.js') }}"></script>
<script src="{{ asset('assets/vendor/hammerjs/hammer.min.js') }}"></script>
<script src="{{ asset('assets/vendor/nanoscroller/bin/javascripts/jquery.nanoscroller.js') }}"></script>
<script src="{{ asset('assets/vendor/bootstrap-slider/dist/bootstrap-slider.min.js') }}"></script>
<script src="{{ asset('assets/js/main.min.js') }}"></script>
<script src="{{ asset('assets/js/main-init.js') }}"></script>
<script src="{{ asset('assets/js/custom.js') }}"></script>
{{--<script src="/assets/vendor/summernote/dist/summernote-bs4.min.js"></script>--}}
